ALTER TABLE `User`
  MODIFY `role` ENUM('CUSTOMER', 'ADMIN', 'OPERATOR', 'CATALOG_MANAGER', 'USER_MANAGER', 'ORDER_MANAGER') NOT NULL DEFAULT 'CUSTOMER';

UPDATE `User`
SET `role` = 'CATALOG_MANAGER'
WHERE `role` = 'OPERATOR';

ALTER TABLE `User`
  MODIFY `role` ENUM('CUSTOMER', 'ADMIN', 'CATALOG_MANAGER', 'USER_MANAGER', 'ORDER_MANAGER') NOT NULL DEFAULT 'CUSTOMER';
