"use client";

import { useState, type FormEvent } from "react";
import { Card, Input, TextArea, toast } from "@heroui/react";
import { Bell, MessageSquareText } from "lucide-react";
import { AdminCheckbox } from "@/components/admin-checkbox";
import { AdminSaveButton } from "@/components/admin-save-button";
import { AdminSectionHelp } from "@/components/admin-section-help";
import { adminFieldClass, adminLabelClass } from "@/components/admin-ui";
import type { CommunicationSettingsData } from "@/modules/communications/communication-settings";

export function CommunicationSettingsForm({ initialSettings }: { initialSettings: CommunicationSettingsData }) {
  const [settings, setSettings] = useState(initialSettings); const [saving, setSaving] = useState(false);
  const set = <K extends keyof CommunicationSettingsData>(key: K, value: CommunicationSettingsData[K]) => setSettings((current) => ({ ...current, [key]: value }));
  const template = (key: keyof CommunicationSettingsData["templates"], value: string) => setSettings((current) => ({ ...current, templates: { ...current.templates, [key]: value } }));
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { const response = await fetch("/api/admin/sms/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.message ?? "تنظیمات ذخیره نشد."); setSettings(result); toast.success("تنظیمات پیامک و اعلان ذخیره شد"); } catch (error) { toast.danger("ذخیره انجام نشد", { description: error instanceof Error ? error.message : "خطای ناشناخته" }); } finally { setSaving(false); } }
  const events = [["orderCreatedSms", "ثبت سفارش", "orderCreated"], ["paymentSuccessSms", "پرداخت موفق", "paymentSuccess"], ["orderShippedSms", "ارسال سفارش", "orderShipped"], ["orderExpiredSms", "انقضای سفارش", "orderExpired"], ["lowStockAdminSms", "هشدار موجودی کم مدیر", "lowStockAdmin"]] as const;
  return <form onSubmit={submit} className="grid gap-5" dir="rtl"><div className="grid items-start gap-5 lg:grid-cols-2"><Card variant="secondary" className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="mb-4 flex items-center gap-2"><Bell size={19} /><h2 className="m-0 text-base font-black">کانال‌ها</h2></div><div className="grid gap-3"><AdminCheckbox isSelected={settings.smsEnabled} onChange={(value) => set("smsEnabled", value)}>ارسال پیامک فعال باشد</AdminCheckbox><AdminCheckbox isSelected={settings.inAppEnabled} onChange={(value) => set("inAppEnabled", value)}>اعلان داخل پنل فعال باشد</AdminCheckbox><label className={adminLabelClass}>شماره مدیر<Input value={settings.adminPhone ?? ""} onChange={(event) => set("adminPhone", event.target.value || null)} dir="ltr" variant="secondary" className={adminFieldClass} placeholder="0912..." /></label></div></Card><Card variant="secondary" className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="mb-4 flex items-center gap-2"><MessageSquareText size={19} /><h2 className="m-0 text-base font-black">رویدادها و متن پیام‌ها</h2><div className="mr-auto"><AdminSectionHelp title="رویدادها و متن پیام‌ها" summary="برای هر رویداد مشخص کنید پیامک ارسال شود و متن نهایی با داده همان سفارش ساخته شود." blocks={[{ title: "فعال‌سازی رویداد", description: "روشن‌بودن کانال پیامک به‌تنهایی کافی نیست؛ سوییچ رویداد موردنظر و یک ارائه‌دهنده فعال نیز لازم است." }, { title: "متغیرهای متن", description: "متغیرهایی مثل {orderNumber} هنگام ارسال با مقدار واقعی جایگزین می‌شوند. نام متغیر و آکولادها را دقیق و بدون فاصله تغییر دهید." }, { title: "متن پیام", items: ["پیام را کوتاه و شفاف نگه دارید.", "نام فروشگاه و اطلاعات ضروری رویداد را ذکر کنید.", "از درج اطلاعات حساس، مبلغ یا لینک ناشناس خودداری کنید."] }, { title: "آزمون", tone: "important", description: "پس از تغییر قالب، یک ارسال آزمایشی به شماره مدیر انجام دهید و نتیجه را در تاریخچه ارائه‌دهنده بررسی کنید." }]} /></div></div><div className="grid gap-4">{events.map(([flag, label, key]) => <div key={flag} className="grid gap-2 rounded-xl border border-[var(--border)] p-3"><AdminCheckbox isSelected={settings[flag]} onChange={(value) => set(flag, value)}>{label}</AdminCheckbox><label className={adminLabelClass}>متن پیام<TextArea rows={2} value={settings.templates[key]} onChange={(event) => template(key, event.target.value)} variant="secondary" className={adminFieldClass} /></label></div>)}</div></Card></div><Card variant="secondary" className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="m-0 text-xs text-[var(--muted)]">متغیرهای قابل استفاده: <code dir="ltr">{"{orderNumber}"}</code>، <code dir="ltr">{"{productName}"}</code> و <code dir="ltr">{"{stock}"}</code></p><AdminSaveButton isSaving={saving} label="ذخیره تنظیمات" /></div></Card></form>;
}
