"use client";

import { useEffect, useState, type FormEvent } from "react";
import { Alert, Button, Card, Chip, TextArea, toast } from "@heroui/react";
import { Send } from "lucide-react";
import { AdminCheckbox } from "@/components/admin-checkbox";
import { HeroSelectField } from "@/components/hero-select-field";
import { adminFieldClass, adminLabelClass } from "@/components/admin-ui";
import { smsAudienceOptions, type SmsAudience } from "@/modules/communications/sms-audiences";

type Campaign = { id: string; audience: string; message: string; recipientCount: number; successfulCount: number; failedCount: number; status: string; createdAt: string };
export function ManualSmsForm({ initialCampaigns }: { initialCampaigns: Campaign[] }) {
  const [audience, setAudience] = useState<SmsAudience>("ALL_OPTED_IN"); const [message, setMessage] = useState(""); const [confirmed, setConfirmed] = useState(false); const [count, setCount] = useState<number | null>(null); const [sending, setSending] = useState(false); const [campaigns, setCampaigns] = useState(initialCampaigns);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/admin/sms/manual?audience=${audience}`, { signal: controller.signal }).then((response) => response.json()).then((result) => setCount(typeof result.count === "number" ? result.count : 0)).catch(() => undefined); return () => controller.abort(); }, [audience]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!confirmed) return; setSending(true); try { const response = await fetch("/api/admin/sms/manual", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ audience, message }) }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.message ?? "ارسال انجام نشد."); toast.success("ارسال پیامک ثبت شد", { description: `${result.recipientCount.toLocaleString("fa-IR")} گیرنده` }); setMessage(""); setConfirmed(false); const history = await fetch("/api/admin/sms/manual").then((item) => item.json()); setCampaigns(history); } catch (error) { toast.danger("ارسال انجام نشد", { description: error instanceof Error ? error.message : "خطای ناشناخته" }); } finally { setSending(false); } }
  return <div className="grid gap-5" dir="rtl"><form onSubmit={submit}><Card variant="secondary" className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="grid items-start gap-5 lg:grid-cols-2"><div className="grid gap-4"><HeroSelectField name="audience" label="گروه مخاطبان" value={audience} onValueChange={(value) => { setCount(null); setAudience(value as SmsAudience); }} options={[...smsAudienceOptions]} /><Alert status="accent"><Alert.Description>{count === null ? "در حال محاسبه مخاطبان..." : `${count.toLocaleString("fa-IR")} کاربر واجد شرایط و دارای رضایت پیامک`}</Alert.Description></Alert></div><div className="grid gap-4"><label className={adminLabelClass}>متن پیامک<TextArea required minLength={3} maxLength={500} rows={5} value={message} onChange={(event) => setMessage(event.target.value)} variant="secondary" className={adminFieldClass} /></label><AdminCheckbox isSelected={confirmed} onChange={setConfirmed}>تعداد مخاطبان و متن پیام را بررسی کردم</AdminCheckbox><Button type="submit" variant="primary" isPending={sending} isDisabled={!confirmed || !message.trim() || !count} className="min-h-11 gap-2"><Send size={16} />ارسال پیامک</Button></div></div></Card></form><Card variant="secondary" className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><div className="border-b border-[var(--border)] p-4"><h2 className="m-0 text-base font-black">ارسال‌های اخیر</h2></div>{campaigns.length ? <div className="divide-y divide-[var(--border)]">{campaigns.map((item) => <div key={item.id} className="grid items-center gap-3 p-4 sm:grid-cols-[minmax(0,1fr)_auto_auto]"><div className="min-w-0"><p className="m-0 truncate text-sm font-bold">{item.message}</p><span className="text-[11px] text-[var(--muted)]">{new Date(item.createdAt).toLocaleString("fa-IR")}</span></div><span className="text-xs">{item.recipientCount.toLocaleString("fa-IR")} گیرنده</span><Chip size="sm" variant="soft"><Chip.Label>{item.status === "SENT" ? "ارسال شد" : item.status === "FAILED" ? "ناموفق" : "در حال ارسال"}</Chip.Label></Chip></div>)}</div> : <div className="p-10 text-center text-xs text-[var(--muted)]">هنوز ارسالی ثبت نشده است.</div>}</Card></div>;
}
