"use client";

import { useEffect, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Alert, Button, Card, Chip, TextArea, toast } from "@heroui/react";
import { Send } from "lucide-react";
import { AdminCheckbox } from "@/components/admin-checkbox";
import { HeroSelectField } from "@/components/hero-select-field";
import { adminFieldClass, adminLabelClass } from "@/components/admin-ui";
import { Table, TableBody, TableCell, TableColumn, TableContent, TableHeader, TableRow, TableScrollContainer } from "@/components/hero";
import { smsAudienceOptions, type SmsAudience } from "@/modules/communications/sms-audiences";

export type SmsCampaignListItem = { id: string; audience: string; message: string; recipientCount: number; successfulCount: number; failedCount: number; status: string; createdAt: string };
export function ManualSmsForm() {
  const router = useRouter();
  const [audience, setAudience] = useState<SmsAudience>("ALL_OPTED_IN"); const [message, setMessage] = useState(""); const [confirmed, setConfirmed] = useState(false); const [count, setCount] = useState<number | null>(null); const [sending, setSending] = useState(false);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/admin/sms/manual?audience=${audience}`, { signal: controller.signal }).then((response) => response.json()).then((result) => setCount(typeof result.count === "number" ? result.count : 0)).catch(() => undefined); return () => controller.abort(); }, [audience]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!confirmed) return; setSending(true); try { const response = await fetch("/api/admin/sms/manual", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ audience, message }) }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.message ?? "ارسال انجام نشد."); toast.success("ارسال پیامک ثبت شد", { description: `${result.recipientCount.toLocaleString("fa-IR")} گیرنده` }); router.push("/admin/settings/notifications/manual"); router.refresh(); } catch (error) { toast.danger("ارسال انجام نشد", { description: error instanceof Error ? error.message : "خطای ناشناخته" }); } finally { setSending(false); } }
  return <form onSubmit={submit} dir="rtl"><Card variant="secondary" className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="grid items-start gap-5 lg:grid-cols-2"><div className="grid gap-4"><HeroSelectField name="audience" label="گروه مخاطبان" value={audience} onValueChange={(value) => { setCount(null); setAudience(value as SmsAudience); }} options={[...smsAudienceOptions]} /><Alert status="accent"><Alert.Description>{count === null ? "در حال محاسبه مخاطبان..." : `${count.toLocaleString("fa-IR")} کاربر واجد شرایط و دارای رضایت پیامک`}</Alert.Description></Alert></div><div className="grid gap-4"><label className={adminLabelClass}>متن پیامک<TextArea required minLength={3} maxLength={500} rows={5} value={message} onChange={(event) => setMessage(event.target.value)} variant="secondary" className={adminFieldClass} /></label><AdminCheckbox isSelected={confirmed} onChange={setConfirmed}>تعداد مخاطبان و متن پیام را بررسی کردم</AdminCheckbox><Button type="submit" variant="primary" isPending={sending} isDisabled={!confirmed || !message.trim() || !count} className="min-h-11 gap-2"><Send size={16} />ارسال پیامک</Button></div></div></Card></form>;
}

export function SmsCampaignList({ items }: { items: SmsCampaignListItem[] }) {
  return <Card variant="secondary" className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)]" dir="rtl">{items.length ? <Table><TableScrollContainer><TableContent aria-label="تاریخچه ارسال دستی پیامک" className="w-full min-w-[760px]"><TableHeader>{["متن پیام", "مخاطبان", "موفق", "ناموفق", "وضعیت", "زمان ارسال"].map((head, index) => <TableColumn id={head} key={head} isRowHeader={index === 0} className="bg-[var(--surface-secondary)] px-4 py-3 text-right text-[11px] font-bold text-[var(--muted)]">{head}</TableColumn>)}</TableHeader><TableBody>{items.map((item) => <TableRow id={item.id} key={item.id}><TableCell className="max-w-sm px-4 py-3 align-middle"><p className="m-0 truncate text-sm font-bold">{item.message}</p></TableCell><TableCell className="px-4 py-3 align-middle">{item.recipientCount.toLocaleString("fa-IR")}</TableCell><TableCell className="px-4 py-3 align-middle text-emerald-700">{item.successfulCount.toLocaleString("fa-IR")}</TableCell><TableCell className="px-4 py-3 align-middle text-rose-600">{item.failedCount.toLocaleString("fa-IR")}</TableCell><TableCell className="px-4 py-3 align-middle"><Chip size="sm" variant="soft"><Chip.Label>{item.status === "SENT" ? "ارسال شد" : item.status === "FAILED" ? "ناموفق" : "در حال ارسال"}</Chip.Label></Chip></TableCell><TableCell className="px-4 py-3 align-middle text-xs text-[var(--muted)]">{new Date(item.createdAt).toLocaleString("fa-IR")}</TableCell></TableRow>)}</TableBody></TableContent></TableScrollContainer></Table> : <div className="p-12 text-center text-xs text-[var(--muted)]">هنوز ارسال دستی ثبت نشده است.</div>}</Card>;
}
