import { notFound, redirect } from "next/navigation";
import { db } from "@/lib/db";
import { formatDate, formatMoney } from "@/lib/format";
import { requireUser } from "@/modules/auth/session";
import type { Prisma } from "@generated/prisma/client";

type InvoiceOrder = Prisma.OrderGetPayload<{include:{invoice:true;items:true;payments:true}}>;
type InvoiceItem = InvoiceOrder["items"][number];
type InvoicePayment = InvoiceOrder["payments"][number];
export const dynamic="force-dynamic";
export default async function InvoicePage({params}:{params:Promise<{orderId:string}>}){const user=await requireUser();const{orderId}=await params;const order=await db.order.findUnique({where:{id:orderId},include:{invoice:true,items:true,payments:true}}) as InvoiceOrder|null;if(!order?.invoice)notFound();if(order.userId!==user.id&&user.role==="CUSTOMER")redirect("/account");const successful=order.payments.find((p: InvoicePayment)=>p.status==="SUCCESS");return <main className="section container"><article className="card card-body" style={{maxWidth:900,margin:"0 auto",padding:36}}><div className="panel-head"><div><span className="eyebrow">فاکتور رسمی فروش</span><h1>زر گالری</h1></div><div><strong>{order.invoice.invoiceNumber}</strong><br/><span className="meta">{formatDate(order.invoice.issuedAt)}</span></div></div><div className="stats" style={{gridTemplateColumns:"1fr 1fr",marginBottom:26}}><div className="stat"><span>شماره سفارش</span><strong style={{fontSize:"1rem"}}>{order.orderNumber}</strong></div><div className="stat"><span>شناسه پرداخت</span><strong style={{fontSize:"1rem"}}>{successful?.referenceId??"—"}</strong></div></div><div className="table-wrap"><table><thead><tr><th>شرح</th><th>وزن</th><th>عیار</th><th>تعداد</th><th>اجرت</th><th>سود</th><th>مالیات</th><th>جمع</th></tr></thead><tbody>{order.items.map((item: InvoiceItem)=><tr key={item.id}><td>{item.name}<br/><span className="meta">{item.sku}</span></td><td>{Number(item.weightGrams)}</td><td>{item.purity}</td><td>{item.quantity}</td><td>{formatMoney(item.makingFee.toString())}</td><td>{formatMoney(item.profit.toString())}</td><td>{formatMoney(item.tax.toString())}</td><td>{formatMoney(item.total.toString())}</td></tr>)}<tr><td colSpan={7}><strong>مبلغ قابل پرداخت</strong></td><td><strong>{formatMoney(order.total.toString())}</strong></td></tr></tbody></table></div><p className="meta" style={{marginTop:24}}>نرخ مبنای طلای ۱۸ عیار در زمان ثبت سفارش: {formatMoney(order.goldPriceSnapshot.toString())}. این فاکتور پس از تأیید پرداخت صادر شده است.</p></article></main>}
